# Generated by Django 5.2.11 on 2026-03-11 04:14

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssignationEvenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_assignation", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Billet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(default="ABC123", max_length=20, unique=True),
                ),
                ("date_emission", models.DateTimeField(auto_now_add=True)),
                ("utilise", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Evenement",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("lieu", models.CharField(max_length=200)),
                ("date_debut", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_fin", models.DateTimeField(default=django.utils.timezone.now)),
                ("capacite_max", models.PositiveIntegerField()),
                (
                    "prix",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("publie", "Publié"),
                            ("annule", "Annulé"),
                            ("termine", "Terminé"),
                        ],
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="EventPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="events/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.IntegerField()),
                ("commentaire", models.TextField(blank=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Inscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("paye", "Payé"),
                            ("annule", "Annulé"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "montant_paye",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("date_inscription", models.DateTimeField(auto_now_add=True)),
                (
                    "reference_paiement",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mot_de_passe", models.CharField(max_length=128)),
                (
                    "role",
                    models.CharField(
                        choices=[("staff", "Staff")], default="staff", max_length=20
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("actif", "Actif"), ("inactif", "Inactif")],
                        default="actif",
                        max_length=20,
                    ),
                ),
                ("telephone", models.CharField(blank=True, max_length=20, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["nom"],
            },
        ),
    ]
