# Generated by Django 5.2.11 on 2026-03-11 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("organisations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evenement",
            name="createur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evenements_crees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evenement",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evenements",
                to="organisations.organisation",
            ),
        ),
        migrations.AddField(
            model_name="assignationevenement",
            name="evenement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_assignes",
                to="events.evenement",
            ),
        ),
        migrations.AddField(
            model_name="eventphoto",
            name="evenement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="events.evenement",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="evenement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="events.evenement",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="inscription",
            name="evenement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inscriptions",
                to="events.evenement",
            ),
        ),
        migrations.AddField(
            model_name="inscription",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="billet",
            name="inscription",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billet",
                to="events.inscription",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff",
                to="organisations.organisation",
            ),
        ),
        migrations.AddField(
            model_name="assignationevenement",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignations",
                to="events.staff",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="feedback",
            unique_together={("participant", "evenement")},
        ),
        migrations.AlterUniqueTogether(
            name="inscription",
            unique_together={("participant", "evenement")},
        ),
        migrations.AlterUniqueTogether(
            name="assignationevenement",
            unique_together={("staff", "evenement")},
        ),
    ]
