# Generated by Django 5.2.11 on 2026-03-19 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("organisations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assignationevenement",
            name="staff",
            field=models.ForeignKey(
                limit_choices_to={"role": "staff"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evenement",
            name="createur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evenements_crees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evenement",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evenements",
                to="organisations.organisation",
            ),
        ),
        migrations.AddField(
            model_name="assignationevenement",
            name="evenement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_assignes",
                to="events.evenement",
            ),
        ),
        migrations.AddField(
            model_name="eventphoto",
            name="evenement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="events.evenement",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assignationevenement",
            unique_together={("staff", "evenement")},
        ),
    ]
