# Generated by Django 5.2.11 on 2026-03-12 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staff",
            old_name="mot_de_passe",
            new_name="password",
        ),
    ]
