# Generated by Django 5.2.11 on 2026-05-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenement",
            name="image_principale",
            field=models.ImageField(blank=True, null=True, upload_to="events/covers/"),
        ),
        migrations.AlterField(
            model_name="evenement",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
