# Generated by Django 5.2.11 on 2026-03-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_rename_mot_de_passe_staff_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="billet",
            name="date_utilisation",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="billet",
            name="code",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
