# Generated by Django 5.2.11 on 2026-08-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_evenement_image_principale_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenement",
            name="secteur",
            field=models.CharField(
                choices=[
                    ("technologie", "Technologie"),
                    ("finance", "Finance"),
                    ("sante", "Santé"),
                    ("education", "Éducation"),
                    ("commerce", "Commerce"),
                    ("autre", "Autre"),
                ],
                default="autre",
                help_text="Secteur d'activité concerné par l'événement",
                max_length=20,
            ),
        ),
    ]
