# Generated by Django 5.2.11 on 2026-03-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_billet_date_utilisation_alter_billet_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billet",
            name="code",
        ),
        migrations.AddField(
            model_name="billet",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="billets_qr/"),
        ),
    ]
