# Generated by Django 5.2.11 on 2026-08-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_evenement_secteur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenement",
            name="secteur",
            field=models.CharField(
                choices=[
                    ("musique", "Musique"),
                    ("tech", "Tech"),
                    ("culture", "Culture"),
                    ("sport", "Sport"),
                    ("business", "Business"),
                    ("formation", "Formation"),
                    ("autre", "Autre"),
                ],
                default="autre",
                help_text="Secteur d'activité concerné par l'événement",
                max_length=20,
            ),
        ),
    ]
