# Generated by Django 5.2.11 on 2026-03-11 04:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InformationOrganisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("siret", models.CharField(blank=True, max_length=14, null=True)),
                ("rcs", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "forme_juridique",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "capital_social",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("iban", models.CharField(blank=True, max_length=34, null=True)),
                ("bic", models.CharField(blank=True, max_length=11, null=True)),
                ("nombre_employes", models.IntegerField(blank=True, null=True)),
                (
                    "chiffre_affaires",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("annee_creation", models.IntegerField(blank=True, null=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("facebook", models.URLField(blank=True, null=True)),
                ("twitter", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("mission", models.TextField(blank=True, null=True)),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DemandeAbonnement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_demande",
                    models.CharField(
                        choices=[
                            ("mensuel", "Mensuel"),
                            ("trimestriel", "Trimestriel"),
                            ("annuel", "Annuel"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "montant_propose",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("raison", models.TextField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("approuve", "Approuvé"),
                            ("refuse", "Refusé"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("date_demande", models.DateTimeField(auto_now_add=True)),
                ("date_traitement", models.DateTimeField(blank=True, null=True)),
                ("commentaire_admin", models.TextField(blank=True, null=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes_abonnement",
                        to="organisations.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gestionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("poste", models.CharField(default="Gestionnaire", max_length=100)),
                (
                    "departement",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("peut_gerer_evenements", models.BooleanField(default=True)),
                ("peut_gerer_finances", models.BooleanField(default=False)),
                ("peut_gerer_personnel", models.BooleanField(default=False)),
                ("peut_voir_rapports", models.BooleanField(default=True)),
                ("actif", models.BooleanField(default=True)),
                ("date_embauche", models.DateField(default=django.utils.timezone.now)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gestionnaires",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["utilisateur__nom", "utilisateur__prenom"],
            },
        ),
    ]
