# Generated by Django 5.2.11 on 2026-03-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proprietaire", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gestionnaire",
            name="date_embauche",
        ),
        migrations.RemoveField(
            model_name="gestionnaire",
            name="poste",
        ),
        migrations.AlterField(
            model_name="gestionnaire",
            name="actif",
            field=models.BooleanField(default=False),
        ),
    ]
