# Generated by Django 5.2.11 on 2026-03-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proprietaire", "0003_remove_gestionnaire_date_embauche_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demandeabonnement",
            name="montant_propose",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="demandeabonnement",
            name="raison",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="demandeabonnement",
            name="type_demande",
            field=models.CharField(
                choices=[
                    ("gratuit", "Gratuit"),
                    ("basique", "Basique"),
                    ("pro", "Pro"),
                    ("premium", "Premium"),
                ],
                max_length=20,
            ),
        ),
    ]
