trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

variables:
  ACR_NAME: eventsaasregistry
  IMAGE_NAME: event-saas-backend
  IMAGE_TAG: latest

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'

- script: |
    pip install -r requirements.txt
  displayName: Install dependencies

- task: Docker@2
  displayName: Build and Push Docker Image
  inputs:
    containerRegistry: 'eventsaasregistry'
    repository: '$(IMAGE_NAME)'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: '$(IMAGE_TAG)'