trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

variables:
  dockerRegistryServiceConnection: 'eventsaasregistry' 
  ACR_LOGIN_SERVER: 'eventsaasregistry.azurecr.io'
  IMAGE_NAME: 'event-saas-backend'
  IMAGE_TAG: '$(Build.BuildId)'

stages:
# --- STAGE 1: TEST ---
- stage: Test
  displayName: "Unit Tests & Coverage"
  jobs:
  - job: RunTests
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.11'

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-django pytest-cov
      displayName: 'Install dependencies'

    - script: |
        # 
        export DJANGO_SETTINGS_MODULE=config.settings.test
        pytest --cov=apps --cov-report=xml --cov-report=term-missing -v
      displayName: 'Run Pytest with SQLite'
      env:

        DEBUG: 'False'

   
    - task: PublishCodeCoverageResults@1
      condition: always()
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      displayName: 'Publish Coverage to Azure'

    - task: PublishTestResults@2
      condition: always()
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/test-*.xml' # Si tu génères un rapport JUnit avec --junitxml
      displayName: 'Publish Test Results to Azure'

# --- STAGE 2: BUILD ---
- stage: Build
  displayName: Build and Push
  dependsOn: Test
  condition: succeeded() # Ne build que si les tests passent
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      displayName: Build and Push to ACR
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(IMAGE_NAME)'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: |
          $(IMAGE_TAG)
          latest

# --- STAGE 3: DEPLOY ---
- stage: Deploy
  displayName: Deploy to Container App
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    steps:
    - task: AzureCLI@2
      displayName: Update Container App
      inputs:
        azureSubscription: 'Azure subscription 1(1b6ca1a5-4833-492a-bb20-b1a8f34a9e50)' 
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az containerapp update \
            --name event-saas-backend \
            --resource-group Eventora \
            --image $(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(Build.BuildId)