# Generated by Django 5.2.11 on 2026-04-08 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RapportIAEvenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume_ia", models.TextField()),
                ("points_amelioration", models.TextField(blank=True, null=True)),
                ("date_generation", models.DateTimeField(auto_now=True)),
                (
                    "evenement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyse_feedback",
                        to="events.evenement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note_globale", models.PositiveSmallIntegerField()),
                ("organisation", models.PositiveSmallIntegerField()),
                ("contenu", models.PositiveSmallIntegerField()),
                ("intervenants", models.PositiveSmallIntegerField()),
                ("lieu", models.PositiveSmallIntegerField()),
                ("ambiance", models.PositiveSmallIntegerField()),
                ("rapport_qualite_prix", models.PositiveSmallIntegerField()),
                ("commentaire", models.TextField(blank=True)),
                ("recommande", models.BooleanField(default=True)),
                ("sentiment_ia", models.CharField(blank=True, max_length=50)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "evenement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="events.evenement",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avis_donnes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("evenement", "participant")},
            },
        ),
    ]
