# Generated by Django 5.2.11 on 2026-04-09 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
        ("organisations", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rapportiaevenement",
            old_name="points_amelioration",
            new_name="aide_decision",
        ),
        migrations.AlterField(
            model_name="feedback",
            name="sentiment_ia",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="RapportGlobalOrganisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analyse_strategique", models.TextField()),
                ("derniere_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapport_ia_global",
                        to="organisations.organisation",
                    ),
                ),
            ],
        ),
    ]
