# Generated by Django 5.2.11 on 2026-03-19 01:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("devise", models.CharField(default="EUR", max_length=10)),
                ("date_paiement", models.DateTimeField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("confirme", "Confirmé"),
                            ("annule", "Annulé"),
                            ("echoue", "Échoué"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("autre", "Autre"),
                        ],
                        default="stripe",
                        max_length=20,
                    ),
                ),
                (
                    "reference_transaction",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
