# Generated by Django 5.2.11 on 2026-03-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paiement",
            name="reference_transaction",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
