# Generated by Django 5.2.11 on 2026-03-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_paiement_reference_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="paiement",
            name="external_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="mode",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("paypal", "PayPal"),
                    ("virement", "Virement"),
                    ("autre", "Autre"),
                ],
                default="stripe",
                max_length=20,
            ),
        ),
    ]
