# Generated by Django 5.2.11 on 2026-03-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_paiement_external_id_alter_paiement_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paiement",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("confirme", "Confirmé"),
                    ("annule", "Annulé"),
                    ("echoue", "Échoué"),
                    ("rembourse", "Remboursé"),
                ],
                default="en_attente",
                max_length=20,
            ),
        ),
    ]
