# Generated by Django 5.2.11 on 2026-03-03 04:09



import django.utils.timezone

from django.db import migrations, models





class Migration(migrations.Migration):



    initial = True



    dependencies = [

        ("auth", "0012_alter_user_first_name_max_length"),

    ]



    operations = [

        migrations.CreateModel(

            name="Utilisateur",

            fields=[

                (

                    "id",

                    models.BigAutoField(

                        auto_created=True,

                        primary_key=True,

                        serialize=False,

                        verbose_name="ID",

                    ),

                ),

                ("password", models.CharField(max_length=128, verbose_name="password")),

                (

                    "last_login",

                    models.DateTimeField(

                        blank=True, null=True, verbose_name="last login"

                    ),

                ),

                (

                    "is_superuser",

                    models.BooleanField(

                        default=False,

                        help_text="Designates that this user has all permissions without explicitly assigning them.",

                        verbose_name="superuser status",

                    ),

                ),

                ("email", models.EmailField(max_length=254, unique=True)),

                ("nom", models.CharField(max_length=100)),

                ("prenom", models.CharField(max_length=100)),

                (

                    "role",

                    models.CharField(

                        choices=[

                            ("proprietaire", "Proprietaire"),

                            ("gestionnaire", "Gestionnaire"),

                            ("staff", "Staff"),

                            ("participant", "Participant"),

                        ],

                        default="participant",

                        max_length=20,

                    ),

                ),

                ("statut", models.CharField(default="actif", max_length=50)),

                (

                    "date_inscription",

                    models.DateTimeField(default=django.utils.timezone.now),

                ),

                ("is_active", models.BooleanField(default=True)),

                ("is_staff", models.BooleanField(default=False)),

                (

                    "groups",

                    models.ManyToManyField(

                        blank=True,

                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",

                        related_name="user_set",

                        related_query_name="user",

                        to="auth.group",

                        verbose_name="groups",

                    ),

                ),

                (

                    "user_permissions",

                    models.ManyToManyField(

                        blank=True,

                        help_text="Specific permissions for this user.",

                        related_name="user_set",

                        related_query_name="user",

                        to="auth.permission",

                        verbose_name="user permissions",

                    ),

                ),

            ],

            options={

                "abstract": False,

            },

        ),

    ]

