# Generated by Django 5.2.11 on 2026-03-14 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="telephone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="statut",
            field=models.CharField(
                choices=[("actif", "Actif"), ("suspendu", "Suspendu")],
                default="actif",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ParticipantProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_naissance", models.DateField(blank=True, null=True)),
                ("adresse", models.TextField(blank=True)),
                ("ville", models.CharField(blank=True, max_length=100)),
                ("code_postal", models.CharField(blank=True, max_length=10)),
                ("profession", models.CharField(blank=True, max_length=100)),
                ("bio", models.TextField(blank=True)),
                ("preferences_evenements", models.JSONField(blank=True, default=list)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
