# Generated by Django 5.2.11 on 2026-03-19 01:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Billet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="billets_qr/"),
                ),
                ("date_emission", models.DateTimeField(auto_now_add=True)),
                ("utilise", models.BooleanField(default=False)),
                ("date_utilisation", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Inscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("paye", "Payé"),
                            ("annule", "Annulé"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "montant_paye",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("date_inscription", models.DateTimeField(auto_now_add=True)),
                (
                    "reference_paiement",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                (
                    "evenement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions",
                        to="events.evenement",
                    ),
                ),
                (
                    "paiement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inscription",
                        to="payments.paiement",
                    ),
                ),
            ],
        ),
    ]
