# Generated by Django 5.2.11 on 2026-03-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inscriptions", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscription",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("paye", "Payé"),
                    ("utilise", "Utilisé"),
                    ("annule", "Annulé"),
                    ("rembourse", "Remboursé"),
                ],
                default="en_attente",
                max_length=20,
            ),
        ),
    ]
