# Generated by Django 5.2.11 on 2026-03-27 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inscriptions", "0003_alter_inscription_statut"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billet",
            name="date_utilisation",
        ),
    ]
