# Generated by Django 5.2.11 on 2026-04-01 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inscriptions", "0004_remove_billet_date_utilisation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inscription",
            options={"ordering": ["-date_inscription"]},
        ),
        migrations.AddField(
            model_name="billet",
            name="date_scan",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="billet",
            name="scanne_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="billets_scannes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
