# Generated by Django 5.2.11 on 2026-04-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inscriptions", "0005_alter_inscription_options_billet_date_scan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscription",
            name="email_feedback_envoye",
            field=models.BooleanField(default=False),
        ),
    ]
