# Generated by Django 5.2.11 on 2026-03-11 04:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Abonnement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mensuel", "Mensuel"),
                            ("trimestriel", "Trimestriel"),
                            ("annuel", "Annuel"),
                        ],
                        default="mensuel",
                        max_length=20,
                    ),
                ),
                ("dateDebut", models.DateField(verbose_name="Date de début")),
                ("dateFin", models.DateField(verbose_name="Date de fin")),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("suspendu", "Suspendu"),
                            ("expiré", "Expiré"),
                            ("en_attente", "En attente"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "dateCreation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=200, verbose_name="Nom de l'organisation"
                    ),
                ),
                (
                    "secteur",
                    models.CharField(
                        choices=[
                            ("technologie", "Technologie"),
                            ("finance", "Finance"),
                            ("sante", "Santé"),
                            ("education", "Éducation"),
                            ("commerce", "Commerce"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Secteur d'activité",
                    ),
                ),
                (
                    "logo",
                    models.TextField(
                        blank=True, null=True, verbose_name="Logo (URL ou base64)"
                    ),
                ),
                (
                    "dateCreation",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "statutAbonnement",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("inactif", "Inactif"),
                            ("essai", "Essai gratuit"),
                            ("suspendu", "Suspendu"),
                        ],
                        default="essai",
                        max_length=20,
                        verbose_name="Statut de l'abonnement",
                    ),
                ),
                (
                    "emailContact",
                    models.EmailField(max_length=254, verbose_name="Email de contact"),
                ),
                (
                    "telephone",
                    models.CharField(max_length=20, verbose_name="Téléphone"),
                ),
                ("adresse", models.TextField(verbose_name="Adresse")),
                (
                    "ville",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Ville"
                    ),
                ),
                (
                    "pays",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Pays"
                    ),
                ),
                (
                    "siteWeb",
                    models.URLField(blank=True, null=True, verbose_name="Site web"),
                ),
                (
                    "abonnement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organisation",
                        to="organisations.abonnement",
                        verbose_name="Abonnement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation",
                "verbose_name_plural": "Organisations",
                "ordering": ["-dateCreation"],
            },
        ),
    ]
