# Generated by Django 5.2.11 on 2026-03-19 01:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Abonnement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("gratuit", "Gratuit"),
                            ("basique", "Basique"),
                            ("pro", "Pro"),
                            ("premium", "Premium"),
                        ],
                        default="gratuit",
                        max_length=20,
                    ),
                ),
                ("date_debut", models.DateField(default=django.utils.timezone.now)),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("suspendu", "Suspendu"),
                            ("expire", "Expiré"),
                        ],
                        default="actif",
                        max_length=20,
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                (
                    "secteur",
                    models.CharField(
                        choices=[
                            ("technologie", "Technologie"),
                            ("finance", "Finance"),
                            ("sante", "Santé"),
                            ("education", "Éducation"),
                            ("commerce", "Commerce"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("email_contact", models.EmailField(max_length=254)),
                ("telephone", models.CharField(max_length=20)),
                ("site_web", models.URLField(blank=True, null=True)),
                ("adresse", models.TextField()),
                ("ville", models.CharField(blank=True, max_length=100, null=True)),
                ("pays", models.CharField(blank=True, max_length=100, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("actif", models.BooleanField(default=True)),
                (
                    "abonnement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organisation",
                        to="organisations.abonnement",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_creation"],
            },
        ),
    ]
