# Generated by Django 5.2.11 on 2026-03-11 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organisations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="proprietaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organisations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Propriétaire",
            ),
        ),
    ]
