# Generated by Django 5.2.11 on 2026-05-03 20:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abonnement",
            name="date_debut",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
