# Generated by Django 5.2.11 on 2026-03-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_notification",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS"), ("push", "Push")],
                        default="email",
                        max_length=20,
                    ),
                ),
                ("sujet", models.CharField(blank=True, max_length=200, null=True)),
                ("message", models.TextField()),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_envoi", models.DateTimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("envoye", "Envoyé"),
                            ("echoue", "Échoué"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
