# Generated by Django 5.2.11 on 2026-04-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="html_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
